[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "file"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[start]
cmd = "bash start.sh"
